export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SUBMIT_ISSUE = 'SUBMIT_ISSUE';
export const RESUBMIT_ISSUE = 'RESUBMIT_ISSUE';
export const CHANGE_ISSUE_STATUS = 'CHANGE_ISSUE_STATUS';